apiVersion: v2
name: dns-sync-gcp
description: DNS Sync/ExternalDNS for GCP
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
  - kubernetes
  - externaldns
  - external-dns
  - dns-sync
  - dns
