apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: istio
spec:
  selector:
    matchExpressions  :
      # Istio typically has:
      # sidecar.istio.io/inject: "true"
      # security.istio.io/tlsMode: istio
      - key: monitoring
        operator: NotIn
        values:
          - "false"

  endpoints:
    # Istio with sidecars uses:
    # prometheus.io/path: /stats/prometheus
    # prometheus.io/port: "15020"
    # prometheus.io/scrape: "true"
    - port: 15020 # "metrics" is recommended, envoy doesn't add containerPort
      interval: 30s
      path: /stats/prometheus # default is /metrics - Istio uses /stats/prometheus
