apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-non-pod-traffic
spec:
  podSelector:
    matchLabels:
      app: dns-gate
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - from:
       - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Release.Namespace }}

