apiVersion: v1
kind: Service
metadata:
  name: dns
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: xdns
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
